language: go
os: linux
dist: xenial
go:
  - '1.13.6'
addons:
  sonarcloud:
    organization: "jpweiser"
    token:
      secure: $TOKEN

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $GOPATH/bin
  - gosec --quiet -fmt sonarqube -out gosec.json -no-fail ./...
  - sonar-scanner