language: go
dist: trusty
go:
  - '1.12.4'
addons:
  sonarcloud:
    organization: "jpweiser"
    token:
      secure: $TOKEN

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $GOPATH/bin
  - gosec ./...
  - sonar-scanner