language: go
os: linux
dist: xenial
go:
  - '1.13.6'
addons:
  sonarcloud:
    organization: "jpweiser"
    token:
      secure: $TOKEN

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - make go/gosec
  - make sonar/gosec